services:
  db:
    image: mariadb:latest
    container_name: teacherhunt-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql  

  teacherhunt-app:
    build: .  
    container_name: teacherhunt-app
    volumes:
      - .:/app  
    ports:
      - "8000:8000"  
    depends_on:
      - db  
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

volumes:
  mariadb_data:
