# Generated by Django 4.2.3 on 2024-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="teachers_image/"),
        ),
    ]
