# Generated by Django 4.2.3 on 2024-09-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teacher_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="k", max_length=255),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="k", max_length=255),
        ),
    ]
