# Generated by Django 4.2.3 on 2024-09-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_subject_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="subjects",
        ),
    ]
