# Generated by Django 4.2.3 on 2024-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_student_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="students_image/"),
        ),
    ]
