# Generated by Django 4.2.3 on 2024-09-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_alter_teacher_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="", max_length=10),
        ),
    ]
