# Generated by Django 4.2.3 on 2024-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_subject_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
