# Generated by Django 4.2.3 on 2024-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_alter_subject_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, default="", related_name="teachers", to="teachers.subject"
            ),
        ),
    ]
