# Generated by Django 4.2.3 on 2024-09-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_alter_teacher_groups_alter_teacher_subjects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subjects",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
