# Generated by Django 5.1.1 on 2024-09-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_teacher_profile_image"),
        ("classroom", "0002_alter_classroom_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("teacher", "student", "start_time", "day_of_class")},
        ),
    ]
