# Generated by Django 5.1.1 on 2024-09-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0005_alter_classroom_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Accepted"), ("C", "Cancelled")],
                default="P",
                max_length=20,
            ),
        ),
    ]
